#!/bin/bash

if [ $# -lt 2 ]; then
  echo "Usage: $(basename $1) REGION FUNCTION [ARGS]..."
  exit 1
fi

REGION=$1
FUNCTION_NAME=$2
shift
shift

TEMPOUT=$(mktemp /tmp/invoke-result.XXXXXX)
TEMPERR=$(mktemp /tmp/invoke-error.XXXXXX)

exec 3>"${TEMPOUT}"
exec 4<"${TEMPOUT}"
exec 5>"${TEMPERR}"
exec 6<"${TEMPERR}"

rm ${TEMPERR}

OUTPUT=$(aws lambda invoke --log-type Tail --region=$REGION --function-name "$FUNCTION_NAME" --payload "`jo -a "$@"`" /proc/self/fd/3 2>&5)
RESPONSE=$(cat <&4)
STDERR=$(cat <&6)

echo $STDERR

echo -e "\033[2m"
echo ${OUTPUT} | jq --raw-output '.LogResult' | base64 -d
echo -e "\033[0m"

echo
echo ${RESPONSE} | jq --raw-output '.output'
